// SPDX-License-Identifier: MIT
// Generated by generator/grammar2decoder.py from the vendored yaml-grammar. Do not edit.
// clang-format off
#ifndef YEAST_DECODER_TABLES_H
#define YEAST_DECODER_TABLES_H

#include <stdint.h>

// A character's key holds the id of the character the grammar names in bits 0..5, one bit per
// character set the grammar tests in bits 6..24, and the bytes the character consumed in bits
// 25..27. Only these two macros know that.
#define YS_LEN(key)            (((key) >> 25) & 0x7u)     // the bytes a character consumed
#define YS_LENGTH_BITS(length) ((uint32_t)(length) << 25) // how the decoder writes them

// The key of each character the grammar names. A character's key is fixed — both its sets and its
// length are — so testing for one is a single comparison.
#define YS_LIT_KEY_CHARACTER_TABULATION      0x03087A01u // U+0009, [032] s-tab
#define YS_LIT_KEY_LINE_FEED                 0x02000242u // U+000A, [024] b-line-feed
#define YS_LIT_KEY_CARRIAGE_RETURN           0x02000243u // U+000D, [025] b-carriage-return
#define YS_LIT_KEY_SPACE                     0x03007A04u // U+0020, [031] s-space, [051] ns-esc-space
#define YS_LIT_KEY_EXCLAMATION_MARK          0x0202FB05u // '!',    [015] c-tag, [090] c-primary-tag-handle, [100] c-non-specific-tag
#define YS_LIT_KEY_QUOTATION_MARK            0x0202EB06u // '"',    [019] c-double-quote, [052] ns-esc-double-quote
#define YS_LIT_KEY_NUMBER_SIGN               0x0202FB07u // '#',    [012] c-comment
#define YS_LIT_KEY_DOLLAR_SIGN               0x0222FA08u // '$',    [039] ns-uri-char
#define YS_LIT_KEY_PERCENT_SIGN              0x0202FB09u // '%',    [020] c-directive
#define YS_LIT_KEY_AMPERSAND                 0x0202FB0Au // '&',    [013] c-anchor
#define YS_LIT_KEY_APOSTROPHE                0x0202BB0Bu // U+0027, [018] c-single-quote
#define YS_LIT_KEY_LEFT_PARENTHESIS          0x0222FA0Cu // '(',    [039] ns-uri-char
#define YS_LIT_KEY_RIGHT_PARENTHESIS         0x0222FA0Du // ')',    [039] ns-uri-char
#define YS_LIT_KEY_ASTERISK                  0x0202FB0Eu // '*',    [014] c-alias
#define YS_LIT_KEY_PLUS_SIGN                 0x0222FA0Fu // '+',    [039] ns-uri-char, [164] c-chomping-indicator
#define YS_LIT_KEY_COMMA                     0x02027B90u // ',',    [007] c-collect-entry
#define YS_LIT_KEY_HYPHEN_MINUS              0x02C2FB11u // '-',    [004] c-sequence-entry
#define YS_LIT_KEY_FULL_STOP                 0x0222FA12u // '.',    [039] ns-uri-char, [087] ns-yaml-version, [204] c-document-end
#define YS_LIT_KEY_SOLIDUS                   0x0222FA13u // '/',    [053] ns-esc-slash
#define YS_LIT_KEY_DIGIT_ZERO                0x02B6FA14u // '0',    [042] ns-esc-null
#define YS_LIT_KEY_COLON                     0x0242FB15u // ':',    [006] c-mapping-value
#define YS_LIT_KEY_SEMICOLON                 0x0222FA16u // ';',    [039] ns-uri-char
#define YS_LIT_KEY_LESS_THAN_SIGN            0x0222FA17u // '<',    [098] c-verbatim-tag
#define YS_LIT_KEY_EQUALS_SIGN               0x0222FA18u // '=',    [039] ns-uri-char
#define YS_LIT_KEY_GREATER_THAN_SIGN         0x0202FB19u // '>',    [017] c-folded
#define YS_LIT_KEY_QUESTION_MARK             0x0242FB1Au // '?',    [005] c-mapping-key
#define YS_LIT_KEY_COMMERCIAL_AT             0x0202FF1Bu // '@',    [021] c-reserved, [022] c-indicator, [039] ns-uri-char
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_A    0x02B3FA1Cu // 'A',    [086] ns-yaml-directive, [088] ns-tag-directive
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_G    0x02A3FA1Du // 'G',    [088] ns-tag-directive
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_L    0x02A3FA1Eu // 'L',    [057] ns-esc-line-separator
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_M    0x02A3FA1Fu // 'M',    [086] ns-yaml-directive
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_N    0x02A3FA20u // 'N',    [055] ns-esc-next-line
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_P    0x02A3FA21u // 'P',    [058] ns-esc-paragraph-separator
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_T    0x02A3FA22u // 'T',    [088] ns-tag-directive
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_U    0x02A3FA23u // 'U',    [061] ns-esc-32-bit
#define YS_LIT_KEY_LATIN_CAPITAL_LETTER_Y    0x02A3FA24u // 'Y',    [086] ns-yaml-directive
#define YS_LIT_KEY_LEFT_SQUARE_BRACKET       0x02027BA5u // '[',    [008] c-sequence-start
#define YS_LIT_KEY_REVERSE_SOLIDUS           0x0222EA26u // U+005C, [041] c-escape, [054] ns-esc-backslash
#define YS_LIT_KEY_RIGHT_SQUARE_BRACKET      0x02027BA7u // ']',    [009] c-sequence-end
#define YS_LIT_KEY_LOW_LINE                  0x0222FA28u // '_',    [056] ns-esc-non-breaking-space
#define YS_LIT_KEY_GRAVE_ACCENT              0x0202FF29u // '`',    [021] c-reserved, [022] c-indicator
#define YS_LIT_KEY_LATIN_SMALL_LETTER_A      0x02B3FA2Au // 'a',    [043] ns-esc-bell
#define YS_LIT_KEY_LATIN_SMALL_LETTER_B      0x02B3FA2Bu // 'b',    [044] ns-esc-backspace
#define YS_LIT_KEY_LATIN_SMALL_LETTER_E      0x02B3FA2Cu // 'e',    [050] ns-esc-escape
#define YS_LIT_KEY_LATIN_SMALL_LETTER_F      0x02B3FA2Du // 'f',    [048] ns-esc-form-feed
#define YS_LIT_KEY_LATIN_SMALL_LETTER_N      0x02A3FA2Eu // 'n',    [046] ns-esc-line-feed
#define YS_LIT_KEY_LATIN_SMALL_LETTER_R      0x02A3FA2Fu // 'r',    [049] ns-esc-carriage-return
#define YS_LIT_KEY_LATIN_SMALL_LETTER_T      0x02ABFA30u // 't',    [045] ns-esc-horizontal-tab
#define YS_LIT_KEY_LATIN_SMALL_LETTER_U      0x02A3FA31u // 'u',    [060] ns-esc-16-bit
#define YS_LIT_KEY_LATIN_SMALL_LETTER_V      0x02A3FA32u // 'v',    [047] ns-esc-vertical-tab
#define YS_LIT_KEY_LATIN_SMALL_LETTER_X      0x02A3FA33u // 'x',    [059] ns-esc-8-bit
#define YS_LIT_KEY_LEFT_CURLY_BRACKET        0x02027BB4u // '{',    [010] c-mapping-start
#define YS_LIT_KEY_VERTICAL_LINE             0x0202FB35u // '|',    [016] c-literal
#define YS_LIT_KEY_RIGHT_CURLY_BRACKET       0x02027BB6u // '}',    [011] c-mapping-end
#define YS_LIT_KEY_TILDE                     0x0222FA37u // '~',    [039] ns-uri-char
#define YS_LIT_KEY_NEXT_LINE                 0x0422FA38u // U+0085, [001] c-printable
#define YS_LIT_KEY_ZERO_WIDTH_NO_BREAK_SPACE 0x06007239u // U+FEFF, [003] c-byte-order-mark

// The sentinels: an id and no set bits, so every membership test fails at them.
#define YS_LIT_KEY_EOF     0x0000003Au // the window is empty
#define YS_LIT_KEY_INVALID 0x0200003Bu // the bytes are not UTF-8

// One bit per character set the grammar tests. The unions and subtractions are already evaluated.
#define YS_SET_BIT_B_CHAR                  0x00000040u // [026] b-char
#define YS_SET_BIT_C_FLOW_INDICATOR        0x00000080u // [023] c-flow-indicator
#define YS_SET_BIT_C_INDICATOR             0x00000100u // [022] c-indicator
#define YS_SET_BIT_C_PRINTABLE             0x00000200u // [001] c-printable
#define YS_SET_BIT_C_RESERVED              0x00000400u // [021] c-reserved
#define YS_SET_BIT_NB_CHAR                 0x00000800u // [027] nb-char
#define YS_SET_BIT_NB_DOUBLE_CHAR_INLINE_0 0x00001000u // [107] nb-double-char
#define YS_SET_BIT_NB_JSON                 0x00002000u // [002] nb-json
#define YS_SET_BIT_NB_SINGLE_CHAR_INLINE_0 0x00004000u // [118] nb-single-char
#define YS_SET_BIT_NS_ANCHOR_CHAR          0x00008000u // [102] ns-anchor-char
#define YS_SET_BIT_NS_ASCII_LETTER         0x00010000u // [037] ns-ascii-letter
#define YS_SET_BIT_NS_CHAR                 0x00020000u // [034] ns-char
#define YS_SET_BIT_NS_DEC_DIGIT            0x00040000u // [035] ns-dec-digit
#define YS_SET_BIT_NS_ESC_HORIZONTAL_TAB   0x00080000u // [045] ns-esc-horizontal-tab
#define YS_SET_BIT_NS_HEX_DIGIT            0x00100000u // [036] ns-hex-digit
#define YS_SET_BIT_NS_PLAIN_FIRST_INLINE_0 0x00200000u // [126] ns-plain-first
#define YS_SET_BIT_NS_PLAIN_FIRST_INLINE_1 0x00400000u // [126] ns-plain-first
#define YS_SET_BIT_NS_WORD_CHAR            0x00800000u // [038] ns-word-char
#define YS_SET_BIT_S_WHITE                 0x01000000u // [033] s-white

// The character sets by id, for ys_scan_set().
typedef enum ys_set_id {
    YS_SET_ID_B_CHAR,
    YS_SET_ID_C_FLOW_INDICATOR,
    YS_SET_ID_C_INDICATOR,
    YS_SET_ID_C_PRINTABLE,
    YS_SET_ID_C_RESERVED,
    YS_SET_ID_NB_CHAR,
    YS_SET_ID_NB_DOUBLE_CHAR_INLINE_0,
    YS_SET_ID_NB_JSON,
    YS_SET_ID_NB_SINGLE_CHAR_INLINE_0,
    YS_SET_ID_NS_ANCHOR_CHAR,
    YS_SET_ID_NS_ASCII_LETTER,
    YS_SET_ID_NS_CHAR,
    YS_SET_ID_NS_DEC_DIGIT,
    YS_SET_ID_NS_ESC_HORIZONTAL_TAB,
    YS_SET_ID_NS_HEX_DIGIT,
    YS_SET_ID_NS_PLAIN_FIRST_INLINE_0,
    YS_SET_ID_NS_PLAIN_FIRST_INLINE_1,
    YS_SET_ID_NS_WORD_CHAR,
    YS_SET_ID_S_WHITE,
    YS_SET_ID_COUNT
} ys_set_id;

// The bit of each character set, indexed by its id.
static const uint32_t YS_SET_BITS[YS_SET_ID_COUNT] = {
    YS_SET_BIT_B_CHAR,                  // [026] b-char
    YS_SET_BIT_C_FLOW_INDICATOR,        // [023] c-flow-indicator
    YS_SET_BIT_C_INDICATOR,             // [022] c-indicator
    YS_SET_BIT_C_PRINTABLE,             // [001] c-printable
    YS_SET_BIT_C_RESERVED,              // [021] c-reserved
    YS_SET_BIT_NB_CHAR,                 // [027] nb-char
    YS_SET_BIT_NB_DOUBLE_CHAR_INLINE_0, // [107] nb-double-char
    YS_SET_BIT_NB_JSON,                 // [002] nb-json
    YS_SET_BIT_NB_SINGLE_CHAR_INLINE_0, // [118] nb-single-char
    YS_SET_BIT_NS_ANCHOR_CHAR,          // [102] ns-anchor-char
    YS_SET_BIT_NS_ASCII_LETTER,         // [037] ns-ascii-letter
    YS_SET_BIT_NS_CHAR,                 // [034] ns-char
    YS_SET_BIT_NS_DEC_DIGIT,            // [035] ns-dec-digit
    YS_SET_BIT_NS_ESC_HORIZONTAL_TAB,   // [045] ns-esc-horizontal-tab
    YS_SET_BIT_NS_HEX_DIGIT,            // [036] ns-hex-digit
    YS_SET_BIT_NS_PLAIN_FIRST_INLINE_0, // [126] ns-plain-first
    YS_SET_BIT_NS_PLAIN_FIRST_INLINE_1, // [126] ns-plain-first
    YS_SET_BIT_NS_WORD_CHAR,            // [038] ns-word-char
    YS_SET_BIT_S_WHITE,                 // [033] s-white
};

// The key of an ASCII character the grammar does not name — one per group of characters that the
// grammar cannot tell apart.
#define YS_KEY_CONTROL    0x02000000u // a C0 control, which belongs to no set at all
#define YS_KEY_DELETE     0x02007000u // U+007F, JSON-compatible but not printable
#define YS_KEY_DIGIT      0x02B6FA00u // '1'..'9' ('0' the grammar names)
#define YS_KEY_HEX_LETTER 0x02B3FA00u // a letter that is also a hexadecimal digit
#define YS_KEY_LETTER     0x02A3FA00u // any other letter
#define YS_KEY_OTHER      0x0222FA00u // printable, and in none of the grammar's classes

// The key of a valid non-ASCII character the grammar does not name, its length bits excluded: such
// a character may be two, three or four bytes long, so decoder.c ORs its length in.
#define YS_KEY_NOT_PRINTABLE 0x00007000u // a C1 control or a noncharacter: JSON-compatible, not printable
#define YS_KEY_CONTENT       0x0022FA00u // an ordinary content character

// The key of every ASCII character. Index it with the byte.
static const uint32_t YS_ASCII[128] = {
    YS_KEY_CONTROL,                    // U+0000
    YS_KEY_CONTROL,                    // U+0001
    YS_KEY_CONTROL,                    // U+0002
    YS_KEY_CONTROL,                    // U+0003
    YS_KEY_CONTROL,                    // U+0004
    YS_KEY_CONTROL,                    // U+0005
    YS_KEY_CONTROL,                    // U+0006
    YS_KEY_CONTROL,                    // U+0007
    YS_KEY_CONTROL,                    // U+0008
    YS_LIT_KEY_CHARACTER_TABULATION,   // U+0009
    YS_LIT_KEY_LINE_FEED,              // U+000A
    YS_KEY_CONTROL,                    // U+000B
    YS_KEY_CONTROL,                    // U+000C
    YS_LIT_KEY_CARRIAGE_RETURN,        // U+000D
    YS_KEY_CONTROL,                    // U+000E
    YS_KEY_CONTROL,                    // U+000F
    YS_KEY_CONTROL,                    // U+0010
    YS_KEY_CONTROL,                    // U+0011
    YS_KEY_CONTROL,                    // U+0012
    YS_KEY_CONTROL,                    // U+0013
    YS_KEY_CONTROL,                    // U+0014
    YS_KEY_CONTROL,                    // U+0015
    YS_KEY_CONTROL,                    // U+0016
    YS_KEY_CONTROL,                    // U+0017
    YS_KEY_CONTROL,                    // U+0018
    YS_KEY_CONTROL,                    // U+0019
    YS_KEY_CONTROL,                    // U+001A
    YS_KEY_CONTROL,                    // U+001B
    YS_KEY_CONTROL,                    // U+001C
    YS_KEY_CONTROL,                    // U+001D
    YS_KEY_CONTROL,                    // U+001E
    YS_KEY_CONTROL,                    // U+001F
    YS_LIT_KEY_SPACE,                  // U+0020
    YS_LIT_KEY_EXCLAMATION_MARK,       // '!'
    YS_LIT_KEY_QUOTATION_MARK,         // '"'
    YS_LIT_KEY_NUMBER_SIGN,            // '#'
    YS_LIT_KEY_DOLLAR_SIGN,            // '$'
    YS_LIT_KEY_PERCENT_SIGN,           // '%'
    YS_LIT_KEY_AMPERSAND,              // '&'
    YS_LIT_KEY_APOSTROPHE,             // U+0027
    YS_LIT_KEY_LEFT_PARENTHESIS,       // '('
    YS_LIT_KEY_RIGHT_PARENTHESIS,      // ')'
    YS_LIT_KEY_ASTERISK,               // '*'
    YS_LIT_KEY_PLUS_SIGN,              // '+'
    YS_LIT_KEY_COMMA,                  // ','
    YS_LIT_KEY_HYPHEN_MINUS,           // '-'
    YS_LIT_KEY_FULL_STOP,              // '.'
    YS_LIT_KEY_SOLIDUS,                // '/'
    YS_LIT_KEY_DIGIT_ZERO,             // '0'
    YS_KEY_DIGIT,                      // '1'
    YS_KEY_DIGIT,                      // '2'
    YS_KEY_DIGIT,                      // '3'
    YS_KEY_DIGIT,                      // '4'
    YS_KEY_DIGIT,                      // '5'
    YS_KEY_DIGIT,                      // '6'
    YS_KEY_DIGIT,                      // '7'
    YS_KEY_DIGIT,                      // '8'
    YS_KEY_DIGIT,                      // '9'
    YS_LIT_KEY_COLON,                  // ':'
    YS_LIT_KEY_SEMICOLON,              // ';'
    YS_LIT_KEY_LESS_THAN_SIGN,         // '<'
    YS_LIT_KEY_EQUALS_SIGN,            // '='
    YS_LIT_KEY_GREATER_THAN_SIGN,      // '>'
    YS_LIT_KEY_QUESTION_MARK,          // '?'
    YS_LIT_KEY_COMMERCIAL_AT,          // '@'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_A, // 'A'
    YS_KEY_HEX_LETTER,                 // 'B'
    YS_KEY_HEX_LETTER,                 // 'C'
    YS_KEY_HEX_LETTER,                 // 'D'
    YS_KEY_HEX_LETTER,                 // 'E'
    YS_KEY_HEX_LETTER,                 // 'F'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_G, // 'G'
    YS_KEY_LETTER,                     // 'H'
    YS_KEY_LETTER,                     // 'I'
    YS_KEY_LETTER,                     // 'J'
    YS_KEY_LETTER,                     // 'K'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_L, // 'L'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_M, // 'M'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_N, // 'N'
    YS_KEY_LETTER,                     // 'O'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_P, // 'P'
    YS_KEY_LETTER,                     // 'Q'
    YS_KEY_LETTER,                     // 'R'
    YS_KEY_LETTER,                     // 'S'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_T, // 'T'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_U, // 'U'
    YS_KEY_LETTER,                     // 'V'
    YS_KEY_LETTER,                     // 'W'
    YS_KEY_LETTER,                     // 'X'
    YS_LIT_KEY_LATIN_CAPITAL_LETTER_Y, // 'Y'
    YS_KEY_LETTER,                     // 'Z'
    YS_LIT_KEY_LEFT_SQUARE_BRACKET,    // '['
    YS_LIT_KEY_REVERSE_SOLIDUS,        // U+005C
    YS_LIT_KEY_RIGHT_SQUARE_BRACKET,   // ']'
    YS_KEY_OTHER,                      // '^'
    YS_LIT_KEY_LOW_LINE,               // '_'
    YS_LIT_KEY_GRAVE_ACCENT,           // '`'
    YS_LIT_KEY_LATIN_SMALL_LETTER_A,   // 'a'
    YS_LIT_KEY_LATIN_SMALL_LETTER_B,   // 'b'
    YS_KEY_HEX_LETTER,                 // 'c'
    YS_KEY_HEX_LETTER,                 // 'd'
    YS_LIT_KEY_LATIN_SMALL_LETTER_E,   // 'e'
    YS_LIT_KEY_LATIN_SMALL_LETTER_F,   // 'f'
    YS_KEY_LETTER,                     // 'g'
    YS_KEY_LETTER,                     // 'h'
    YS_KEY_LETTER,                     // 'i'
    YS_KEY_LETTER,                     // 'j'
    YS_KEY_LETTER,                     // 'k'
    YS_KEY_LETTER,                     // 'l'
    YS_KEY_LETTER,                     // 'm'
    YS_LIT_KEY_LATIN_SMALL_LETTER_N,   // 'n'
    YS_KEY_LETTER,                     // 'o'
    YS_KEY_LETTER,                     // 'p'
    YS_KEY_LETTER,                     // 'q'
    YS_LIT_KEY_LATIN_SMALL_LETTER_R,   // 'r'
    YS_KEY_LETTER,                     // 's'
    YS_LIT_KEY_LATIN_SMALL_LETTER_T,   // 't'
    YS_LIT_KEY_LATIN_SMALL_LETTER_U,   // 'u'
    YS_LIT_KEY_LATIN_SMALL_LETTER_V,   // 'v'
    YS_KEY_LETTER,                     // 'w'
    YS_LIT_KEY_LATIN_SMALL_LETTER_X,   // 'x'
    YS_KEY_LETTER,                     // 'y'
    YS_KEY_LETTER,                     // 'z'
    YS_LIT_KEY_LEFT_CURLY_BRACKET,     // '{'
    YS_LIT_KEY_VERTICAL_LINE,          // '|'
    YS_LIT_KEY_RIGHT_CURLY_BRACKET,    // '}'
    YS_LIT_KEY_TILDE,                  // '~'
    YS_KEY_DELETE,                     // U+007F
};

#endif // YEAST_DECODER_TABLES_H
// clang-format on
